name: Build kernel image (cargo bootimage)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src
        profile: minimal

    - name: Set nightly as default
      run: rustup default nightly

    - name: Add target
      run: rustup target add x86_64-unknown-none

    - name: Install bootimage in version (0.10.0) 
      run: cargo install bootimage --version "^0.10.0" -j $(nproc)
    - name: Build Renux kernel image
      run: cargo bootimage --target x86_64-unknown-none -j $(nproc)
