name: Format Code

on:
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  rustfmt:
    name: Run rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Set nightly as default
        run: rustup default nightly

      - name: Format code
        run: cargo fmt
