name: Update Kernel Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update kernel submodule
        run: |
          git submodule update --remote --merge --allow-unrelated-histories
          git add kernel
          git commit -m "Update kernel submodule"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
