name: Update Kernel Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Update kernel submodule
      run: |
        git submodule update --remote --merge
        git add kernel
        git commit -m "Update kernel submodule"
        git push origin main

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update kernel submodule'
          git push
        else
          echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.WORK_BOT }}
